# Mauro Ziliani <mauro@faresoftware.it>
#
# Some variables to configure icecream script
# ICECCD_BIN=
# ICECC_SCHEDULER_BIN=
# ICECREAM_BASEDIR=
# ICECREAM_VERBOSITY=
# ICECREAM_NETNAME=
# ICECREAM_LOG_FILE=
# ICECREAM_NICE_LEVEL=
# ICECREAM_SCHEDULER_HOST=
# ICECREAM_RUN_SCHEDULER=
# ICECREAM_ALLOW_REMOTE=
# ICECREAM_MAX_JOBS=
# ICECREAM_SCHEDULER_LOG_FILE=
